name: ci
on:
  push:
  schedule:
    - cron: "0 7 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: 0.13.0

    - name: Build
      run: zig build

        #- name: Test
        #  run: zig build test

    - name: Packaging Dry Run
      run: zig build package -- https://github.com/mattnite/c-packages/releases/download
      if: ${{ matrix.os == 'macos-latest' }}
